#ifndef GPIO_CONFIG_H_
#define GPIO_CONFIG_H_


/*  configuration for CFG macro
 * 	INPUT_ANALOG
 *  INPUT_FLOATING
 *  INPUT_PULL_UP_OR_DOWN
 *
 *  OUTPUT_PUSH_PULL
 *  OUTPUT_OPEN_DRAIN
 *  AF_PUSH_PULL
 *  AF_OPEN_DRAIN
 * */

/* Configurations for MODE macro
 *
 *  INPUT_MODE
 *  OUTPUT_10MHZ
 *  OUTPUT_2MHZ
 *  OUTPUT_50MHZ
 * */
/*PORT A configurations*/
#define PORTA_MODE0 OUTPUT_2MHZ
#define PORTA_CFG0  OUTPUT_PUSH_PULL

#define PORTA_MODE1 OUTPUT_2MHZ
#define PORTA_CFG1  OUTPUT_PUSH_PULL

#define PORTA_MODE2  OUTPUT_2MHZ
#define PORTA_CFG2   OUTPUT_PUSH_PULL

#define PORTA_MODE3   OUTPUT_2MHZ
#define PORTA_CFG3    OUTPUT_PUSH_PULL

#define PORTA_MODE4   OUTPUT_2MHZ
#define PORTA_CFG4    OUTPUT_PUSH_PULL

#define PORTA_MODE5   OUTPUT_2MHZ
#define PORTA_CFG5    OUTPUT_PUSH_PULL

#define PORTA_MODE6   OUTPUT_2MHZ
#define PORTA_CFG6    OUTPUT_PUSH_PULL

#define PORTA_MODE7   OUTPUT_2MHZ
#define PORTA_CFG7    OUTPUT_PUSH_PULL

#define PORTA_MODE8    OUTPUT_2MHZ
#define PORTA_CFG8     OUTPUT_PUSH_PULL

#define PORTA_MODE9     OUTPUT_2MHZ
#define PORTA_CFG9      OUTPUT_PUSH_PULL

#define PORTA_MODE10  OUTPUT_2MHZ
#define PORTA_CFG10   OUTPUT_PUSH_PULL

#define PORTA_MODE11   OUTPUT_2MHZ
#define PORTA_CFG11    OUTPUT_PUSH_PULL

#define PORTA_MODE12   OUTPUT_2MHZ
#define PORTA_CFG12    OUTPUT_PUSH_PULL

#define PORTA_MODE13    OUTPUT_2MHZ
#define PORTA_CFG13     OUTPUT_PUSH_PULL

#define PORTA_MODE14     OUTPUT_2MHZ
#define PORTA_CFG14      OUTPUT_PUSH_PULL

#define PORTA_MODE15     OUTPUT_2MHZ
#define PORTA_CFG15      OUTPUT_PUSH_PULL
/*End configuration for PORTA*/


/*PORTB*/
#define PORTB_MODE0 			OUTPUT_2MHZ
#define PORTB_CFG0  			OUTPUT_PUSH_PULL

#define PORTB_MODE1				OUTPUT_2MHZ
#define PORTB_CFG1  			OUTPUT_PUSH_PULL

#define PORTB_MODE2  			OUTPUT_2MHZ
#define PORTB_CFG2   			OUTPUT_PUSH_PULL

#define PORTB_MODE3   			OUTPUT_2MHZ
#define PORTB_CFG3    			OUTPUT_PUSH_PULL

#define PORTB_MODE4   			OUTPUT_2MHZ
#define PORTB_CFG4    			OUTPUT_PUSH_PULL

#define PORTB_MODE5   			OUTPUT_2MHZ
#define PORTB_CFG5    			OUTPUT_PUSH_PULL

#define PORTB_MODE6   			OUTPUT_2MHZ
#define PORTB_CFG6    			OUTPUT_PUSH_PULL

#define PORTB_MODE7   			OUTPUT_2MHZ
#define PORTB_CFG7    			OUTPUT_PUSH_PULL

#define PORTB_MODE8    			OUTPUT_2MHZ
#define PORTB_CFG8     			OUTPUT_PUSH_PULL

#define PORTB_MODE9     		OUTPUT_2MHZ
#define PORTB_CFG9      		OUTPUT_PUSH_PULL

#define PORTB_MODE10  			OUTPUT_2MHZ
#define PORTB_CFG10   			OUTPUT_PUSH_PULL

#define PORTB_MODE11   			OUTPUT_2MHZ
#define PORTB_CFG11    			OUTPUT_PUSH_PULL

#define PORTB_MODE12   			OUTPUT_2MHZ
#define PORTB_CFG12    			OUTPUT_PUSH_PULL

#define PORTB_MODE13    		OUTPUT_2MHZ
#define PORTB_CFG13     		OUTPUT_PUSH_PULL

#define PORTB_MODE14    		OUTPUT_2MHZ
#define PORTB_CFG14      		OUTPUT_PUSH_PULL

#define PORTB_MODE15     		OUTPUT_2MHZ
#define PORTB_CFG15     		OUTPUT_PUSH_PULL

/*End configuration for PORTB*/




#endif
